export default {

    // Book Actions
    SELECT_BOOK: 'SELECT_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    FAV_BOOK: 'FAV_BOOK',

    // Course Actions
    ADD_COURSE: 'ADD_COURSE',
    SELECT_COURSE: 'SELECT_COURSE',
    REMOVE_COURSE: 'REMOVE_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    FAV_COURSE: 'FAV_COURSE',

    // Project Actions
    ADD_PROJECT: "ADD_PROJECT",
    SELECT_PROJECT: "SELECT_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    FAV_PROJECT: "FAV_PROJECT",
};