export default {

    // Book Actions
    SELECT_BOOK: 'SELECT_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    FAV_BOOK: 'FAV_BOOK',

    // CourseQuery Actions
    UPDATE_COURSE_QUERY_RESULTS: 'UPDATE_COURSE_QUERY_RESULTS',
    SELECT_COURSE_QUERY_RESULT: 'SELECT_COURSE_QUERY_RESULT',

    // Coursereview Actions
    ADD_COURSE_REVIEW: 'ADD_COURSEREVIEW',
    SELECT_COURSE_REVIEW: 'SELECT_COURSE_REVIEW',
    REMOVE_COURSE_REVIEW: 'REMOVE_COURSEREVIEW',
    UPDATE_COURSE_REVIEW: 'UPDATE_COURSEREVIEW',
    FAV_COURSE_REVIEW: 'FAV_COURSE_REVIEW',

    // Project Actions
    ADD_PROJECT: "ADD_PROJECT",
    SELECT_PROJECT: "SELECT_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    FAV_PROJECT: "FAV_PROJECT",
};