export default {

    // Book Actions
    SELECT_BOOK: 'SELECT_BOOK',
    ADD_BOOK: 'ADD_BOOK',
    UPDATE_BOOK: 'UPDATE_BOOK',
    FAV_BOOK: 'FAV_BOOK',

    // Course Actions
    
    LOAD_COURSE_SUCCESS: 'LOAD_COURSE_SUCCESS',
    SELECT_COURSE: 'SELECT_COURSE',
    FAV_COURSE: 'FAV_COURSE',

    // Coursereview Actions
    FETCH_COURSE_REVIEWS: 'FETCH_COURSE_REVIEWS',
    ADD_COURSE_REVIEW: 'ADD_COURSEREVIEW',
    SELECT_COURSE_REVIEW: 'SELECT_COURSE_REVIEW',
    REMOVE_COURSE_REVIEW: 'REMOVE_COURSEREVIEW',
    UPDATE_COURSE_REVIEW: 'UPDATE_COURSEREVIEW',
    FAV_COURSE_REVIEW: 'FAV_COURSE_REVIEW',
    
    // ----Success messages
    LOAD_COURSE_REVIEW_SUCCESS: 'LOAD_COURSE_REVIEW_SUCCESS',
    ADD_COURSE_REVIEW_SUCCESS: 'ADD_COURSE_REVIEW_SUCCESS',
    UPDATE_COURSE_REVIEW_SUCCESS: 'UPDATE_COURSE_REVIEW_SUCCESS',

    // Project Actions
    ADD_PROJECT: "ADD_PROJECT",
    SELECT_PROJECT: "SELECT_PROJECT",
    REMOVE_PROJECT: "REMOVE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    FAV_PROJECT: "FAV_PROJECT",
};